[package]
name = "compile_link_c_lib"
version = "0.1.0"
edition = "2021"
build = "build.rs"
[build-dependencies]
cc = "1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error-chain = "0.12.4"
